
all: check

check: 01-simple 02-path-building 03-directory-listing

01-simple:
	guile ./01-simple.scm

02-path-building:
	guile ./02-path-building.scm

03-directory-listing:
	guile ./03-directory-listing.scm
